
export const SCENARIOS_GET = 'SCENARIOS_GET'
export const SCENARIOS_REFRESH = 'SCENARIOS_REFRESH'
export const SCENARIOS_SELECT = 'SCENARIOS_SELECT'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
